# Generated by Django 6.0.3 on 2026-03-16 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_rename_bike_number_driver_vehicle_number_and_more'),
        ('rides', '0002_alter_ride_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.driver'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='drop_location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ride',
            name='fare',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('accepted', 'Accepted'), ('started', 'Started'), ('completed', 'Completed')], default='booked', max_length=20),
        ),
    ]
