# Generated by Django 6.0.3 on 2026-03-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_alter_ride_driver_alter_ride_drop_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='commission',
            field=models.FloatField(default=0),
        ),
    ]
