# Generated by Django 6.0.3 on 2026-03-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='bike_number',
            new_name='vehicle_number',
        ),
        migrations.AddField(
            model_name='driver',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
